// Component dependency metadata used by source analysis and AI prompts.
export const COMPONENT_DEPENDENCIES: Record<string, string[]> = {
  'animated-content': ['gsap'],
  'animated-list': ['motion-v'],
  antigravity: ['three'],
  'ascii-text': ['three'],
  aurora: ['ogl'],
  balatro: ['ogl'],
  ballpit: ['gsap', 'three'],
  beams: ['three'],
  'blob-cursor': ['gsap'],
  'blur-text': ['motion-v'],
  'bounce-cards': ['gsap'],
  'bubble-menu': ['gsap'],
  'card-nav': ['gsap'],
  'card-swap': ['gsap'],
  carousel: ['motion-v'],
  'chroma-grid': ['gsap'],
  'circular-gallery': ['ogl'],
  'circular-text': ['motion-v'],
  'color-bends': ['three'],
  counter: ['motion-v'],
  crosshair: ['gsap'],
  cubes: ['gsap'],
  'dark-veil': ['ogl'],
  'decay-card': ['gsap'],
  dither: ['ogl'],
  dock: ['motion-v'],
  'dot-grid': ['gsap'],
  'evil-eye': ['ogl'],
  'fade-content': ['gsap'],
  'falling-text': ['matter-js'],
  'faulty-terminal': ['ogl'],
  ferrofluid: ['ogl'],
  'floating-lines': ['three'],
  'flowing-menu': ['gsap'],
  'flying-posters': ['ogl'],
  galaxy: ['ogl'],
  'ghost-cursor': ['three'],
  'gradient-blinds': ['ogl'],
  'gradient-text': ['motion-v'],
  grainient: ['ogl'],
  'grid-distortion': ['three'],
  'grid-motion': ['gsap'],
  'grid-scan': ['face-api.js', 'postprocessing', 'three'],
  hyperspeed: ['three', 'postprocessing'],
  'image-trail': ['gsap'],
  'infinite-menu': ['gl-matrix'],
  iridescence: ['ogl'],
  'laser-flow': ['three'],
  'light-pillar': ['three'],
  'light-rays': ['ogl'],
  lightfall: ['ogl'],
  'line-waves': ['ogl'],
  'liquid-chrome': ['ogl'],
  'liquid-ether': ['three'],
  'magic-bento': ['gsap'],
  'magic-rings': ['three'],
  masonry: ['gsap'],
  'meta-balls': ['ogl'],
  'model-viewer': ['three', '@tresjs/core', '@tresjs/cientos'],
  orb: ['ogl'],
  particles: ['ogl'],
  'pill-nav': ['gsap'],
  'pixel-blast': ['postprocessing', 'three'],
  'pixel-snow': ['three'],
  'pixel-trail': ['three'],
  'pixel-transition': ['gsap'],
  plasma: ['ogl'],
  'plasma-wave': ['ogl'],
  prism: ['ogl'],
  'prismatic-burst': ['ogl'],
  radar: ['ogl'],
  'reflective-card': ['lucide-vue-next'],
  ribbons: ['ogl'],
  'ripple-grid': ['ogl'],
  'rotating-text': ['motion-v'],
  'scramble-text': ['gsap'],
  'scroll-float': ['gsap'],
  'scroll-reveal': ['gsap'],
  'scroll-stack': ['lenis'],
  'scroll-velocity': ['gsap'],
  'shape-blur': ['three'],
  'shiny-text': ['motion-v'],
  shuffle: ['gsap'],
  'side-rays': ['ogl'],
  silk: ['ogl'],
  'soft-aurora': ['ogl'],
  'split-text': ['gsap'],
  stack: ['motion-v'],
  'staggered-menu': ['gsap'],
  stepper: ['motion-v'],
  'sticker-peel': ['gsap'],
  strands: ['ogl'],
  'target-cursor': ['gsap'],
  'text-cursor': ['motion-v'],
  'text-type': ['gsap'],
  threads: ['ogl'],
  'tilted-card': ['motion-v'],
  'true-focus': ['motion-v']
};

export function dependenciesForSlug(slug: string | undefined): string[] {
  return slug ? (COMPONENT_DEPENDENCIES[slug] ?? []) : [];
}
